FROM php:8.2-fpm
# Maintainer : yenchen yenchen.chen@uqconnect.edu.au
LABEL maintainer="yenchen.chen@uqconnect.edu.au"

# ENV PHP_VERSION
ENV TZ=Australia/Sydney

RUN apt-get update && \
    apt-get install -y libzip-dev zip && \
    docker-php-ext-install mysqli && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean


# Expose port
EXPOSE 9000

