FROM php:8.2-fpm
# Maintainer : yenchen yenchen.chen@uqconnect.edu.au
LABEL maintainer="yenchen.chen@uqconnect.edu.au"

# ENV PHP_VERSION
ENV TZ=Australia/Sydney

RUN apt-get update && \
    apt-get install -y \
        libzip-dev \
        zip \
        libicu-dev \
        --no-install-recommends && \
    docker-php-ext-configure intl && \
    docker-php-ext-install \
        mysqli \
        intl \
        zip && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Copy the entrypoint script into the image
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

# Expose port
EXPOSE 9000
ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
